//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesDatos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesDatos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datos.ResourcesDatos", typeof(ResourcesDatos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el archivo config.xml.
        /// </summary>
        internal static string ConfigXMLNoExiste {
            get {
                return ResourceManager.GetString("ConfigXMLNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el proceso.
        /// </summary>
        internal static string ErrorProceso {
            get {
                return ResourceManager.GetString("ErrorProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizo correctamente el proceso de grabación .
        /// </summary>
        internal static string ProcesoFinalizado {
            get {
                return ResourceManager.GetString("ProcesoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando Grabación.
        /// </summary>
        internal static string RealizandoGrabacion {
            get {
                return ResourceManager.GetString("RealizandoGrabacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATHAGRO.
        /// </summary>
        internal static string XMLParamPATHAGRO {
            get {
                return ResourceManager.GetString("XMLParamPATHAGRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATHEST.
        /// </summary>
        internal static string XMLParamPATHEST {
            get {
                return ResourceManager.GetString("XMLParamPATHEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATHESTLOCAL.
        /// </summary>
        internal static string XMLParamPATHESTLOCAL {
            get {
                return ResourceManager.GetString("XMLParamPATHESTLOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATHGEST.
        /// </summary>
        internal static string XMLParamPATHGEST {
            get {
                return ResourceManager.GetString("XMLParamPATHGEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cSPSearch.
        /// </summary>
        internal static string XMLParamSearch {
            get {
                return ResourceManager.GetString("XMLParamSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cStoreProcedure.
        /// </summary>
        internal static string XMLParamSP {
            get {
                return ResourceManager.GetString("XMLParamSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cStrCon.
        /// </summary>
        internal static string XMLParamStringConexion {
            get {
                return ResourceManager.GetString("XMLParamStringConexion", resourceCulture);
            }
        }
    }
}
